### ISSUE TITLE
from pyserini.search import querybuilder

### ISSUE THREAD

**Issue by hosseinfani** [hosseinfani/ReQue#18]
I've created the ReQue environment successfully. Also, the pyserini is already installed as seen in the second paragraph. However, when run the main.py or explicitly import the querybuilder from pyserini.search (third paragraph), I receive the "DLL load failed" error.

(ReQue) C:\ReQue\develop\qe>python main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from pyserini.search import querybuilder
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\search\__init__.py", line 17, in <module>
    from ._base import Document, JDocument, JQuery, get_topics, get_topics_with_reader
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\search\_base.py", line 24, in <module>
    from ..pyclass import autoclass, JPaths
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\pyclass.py", line 27, in <module>
    from jnius import autoclass, cast
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\jnius\__init__.py", line 41, in <module>
    from .jnius import *  # noqa
ImportError: DLL load failed: The specified module could not be found.

(ReQue) C:\ReQue\develop\qe>pip install pyserini
Requirement already satisfied: pyserini in c:\programdata\anaconda3\envs\reque\lib\site-packages (0.9.4.0)
Requirement already satisfied: pyjnius in c:\programdata\anaconda3\envs\reque\lib\site-packages (from pyserini) (1.3.0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\envs\reque\lib\site-packages (from pyserini) (1.18.1)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\envs\reque\lib\site-packages (from pyserini) (0.23.2)
Requirement already satisfied: scipy in c:\programdata\anaconda3\envs\reque\lib\site-packages (from pyserini) (1.4.1)
Requirement already satisfied: pandas in c:\programdata\anaconda3\envs\reque\lib\site-packages (from pyserini) (0.23.3)
Requirement already satisfied: Cython in c:\programdata\anaconda3\envs\reque\lib\site-packages (from pyserini) (0.29.21)
Requirement already satisfied: six>=1.7.0 in c:\programdata\anaconda3\envs\reque\lib\site-packages (from pyjnius->pyserini) (1.15.0)
Requirement already satisfied: joblib>=0.11 in c:\programdata\anaconda3\envs\reque\lib\site-packages (from scikit-learn->pyserini) (0.17.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\envs\reque\lib\site-packages (from scikit-learn->pyserini) (2.1.0)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\programdata\anaconda3\envs\reque\lib\site-packages (from pandas->pyserini) (2.8.1)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda3\envs\reque\lib\site-packages (from pandas->pyserini) (2020.1)

(ReQue) C:\ReQue\develop\qe>python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyserini
>>> from pyserini.search import querybuilder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\search\__init__.py", line 17, in <module>
    from ._base import Document, JDocument, JQuery, get_topics, get_topics_with_reader
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\search\_base.py", line 24, in <module>
    from ..pyclass import autoclass, JPaths
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\pyclass.py", line 27, in <module>
    from jnius import autoclass, cast
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\jnius\__init__.py", line 41, in <module>
    from .jnius import *  # noqa
ImportError: DLL load failed: The specified module could not be found.

>>> from pyserini.search import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\search\__init__.py", line 17, in <module>
    from ._base import Document, JDocument, JQuery, get_topics, get_topics_with_reader
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\search\_base.py", line 24, in <module>
    from ..pyclass import autoclass, JPaths
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\pyclass.py", line 27, in <module>
    from jnius import autoclass, cast
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\jnius\__init__.py", line 41, in <module>
    from .jnius import *  # noqa
ImportError: DLL load failed: The specified module could not be found.

**Comment by hosseinfani** [comment]
The original solution is here: https://github.com/kivy/pyjnius/issues/216

We have to either programmatically or manually set the environment variables for java home directory

Programatically in python: 
import os
os.environ['JDK_HOME'] = "C:\Program Files\Java\jdk1.XXX"
os.environ['JAVA_HOME'] = "C:\Program Files\Java\jdk1.XXX"
os.environ['PATH'] += ';C:\\Program Files\\Java\\jdk1.XXX\\jre\\bin\\server\\;C:\\Program Files\\Java\\jdk1.XXX\\bin\\;path\to\your.jar'
