### ISSUE TITLE
PYWSD: cannot import name 'WordNet' from 'wn' 

### ISSUE THREAD

**Issue by hosseinfani** [hosseinfani/ReQue#19]
(ReQue) C:\Users\hfani\Documents\ReQue\develop\qe>python main.py
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    from cmn import expander_factory as ef
  File "C:\Users\hfani\Documents\ReQue\develop\qe\cmn\expander_factory.py", line 7, in <module>
    from expanders.sensedisambiguation import SenseDisambiguation
  File "C:\Users\hfani\Documents\ReQue\develop\qe\expanders\sensedisambiguation.py", line 1, in <module>
    from pywsd import disambiguate
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pywsd\__init__.py", line 14, in <module>
    from wn import WordNet
ImportError: cannot import name 'WordNet' from 'wn' (C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\wn\__init__.py)

**Comment by Michelle-Watson** [comment]
Any update on this issue? I'm having the same problem

**Comment by hosseinfani** [comment]
Seems there is a dependency conflict for pywsd library. See [here ](https://github.com/alvations/pywsd/issues/62)for the full story.
So, we have to fix the wordnet version to 0.0.23. We did that in our environment.yml. 
One can downgrade wn to this version by 
pip install -U wn=0.0.23

**Comment by bhrt-sharma** [comment]
it was actually 
pip install -U wn==0.0.22
that worked for me on python3.8 environment.
