### ISSUE TITLE
cannot import name 'JSimpleSearcherResult' from 'pyserini.pyclass'

### ISSUE THREAD

**Issue by hosseinfani** [hosseinfani/ReQue#20]
(ReQue) C:\Users\hfani\Documents\ReQue\develop\qe>python main.py
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    from expanders.bertqe import BertQE
  File "C:\Users\hfani\Documents\ReQue\develop\qe\expanders\bertqe.py", line 13, in <module>
    from pygaggle.rerank.base import Query, Text
  File "C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pygaggle\rerank\base.py", line 4, in <module>
    from pyserini.pyclass import JSimpleSearcherResult
ImportError: cannot import name 'JSimpleSearcherResult' from 'pyserini.pyclass' (C:\ProgramData\Anaconda3\envs\ReQue\lib\site-packages\pyserini\pyclass.py)

**Comment by hosseinfani** [comment]
This is a bug to pygaggle. See [here](https://github.com/castorini/pygaggle/issues/125) for the related issue.

**Comment by hosseinfani** [comment]
pygaggle's master is compatible with pyserini 0.10. So, I removed the pygaggle installer from environment.yml and requirement.txt. We have to clone or install it after conda env creation it for now till they release their new version.
